/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardCallsRouteImport } from './routes/dashboard/calls'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard/conversations'
import { Route as DashboardKnowledgeRouteImport } from './routes/dashboard/knowledge'
import { Route as DashboardNumbersRouteImport } from './routes/dashboard/numbers'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardUsageRouteImport } from './routes/dashboard/usage'
import { Route as DashboardVoiceRouteImport } from './routes/dashboard/voice'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard/whatsapp'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AdminCompaniesCompanyIdRouteImport } from './routes/admin_.companies.$companyId'
import { Route as ApiCronJobRouteImport } from './routes/api/cron/$job'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'
import { Route as ApiPublicWebhooksProviderRouteImport } from './routes/api/public/webhooks/$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCallsRoute = DashboardCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKnowledgeRoute = DashboardKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNumbersRoute = DashboardNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVoiceRoute = DashboardVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesCompanyIdRoute = AdminCompaniesCompanyIdRouteImport.update({
  id: '/admin_/companies/$companyId',
  path: '/admin/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronJobRoute = ApiCronJobRouteImport.update({
  id: '/api/cron/$job',
  path: '/api/cron/$job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksProviderRoute =
  ApiPublicWebhooksProviderRouteImport.update({
    id: '/api/public/webhooks/$provider',
    path: '/api/public/webhooks/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/numbers': typeof DashboardNumbersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/api/cron/$job': typeof ApiCronJobRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/numbers': typeof DashboardNumbersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/api/cron/$job': typeof ApiCronJobRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/numbers': typeof DashboardNumbersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin_/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
  '/api/cron/$job': typeof ApiCronJobRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/onboarding'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard/agents'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/conversations'
    | '/dashboard/knowledge'
    | '/dashboard/numbers'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/usage'
    | '/dashboard/voice'
    | '/dashboard/whatsapp'
    | '/invite/$token'
    | '/dashboard/'
    | '/admin/companies/$companyId'
    | '/api/cron/$job'
    | '/api/public/calendar/$token'
    | '/api/public/webhooks/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/onboarding'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard/agents'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/conversations'
    | '/dashboard/knowledge'
    | '/dashboard/numbers'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/usage'
    | '/dashboard/voice'
    | '/dashboard/whatsapp'
    | '/invite/$token'
    | '/dashboard'
    | '/admin/companies/$companyId'
    | '/api/cron/$job'
    | '/api/public/calendar/$token'
    | '/api/public/webhooks/$provider'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/onboarding'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard/agents'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/conversations'
    | '/dashboard/knowledge'
    | '/dashboard/numbers'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/usage'
    | '/dashboard/voice'
    | '/dashboard/whatsapp'
    | '/invite/$token'
    | '/dashboard/'
    | '/admin_/companies/$companyId'
    | '/api/cron/$job'
    | '/api/public/calendar/$token'
    | '/api/public/webhooks/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  AdminCompaniesCompanyIdRoute: typeof AdminCompaniesCompanyIdRoute
  ApiCronJobRoute: typeof ApiCronJobRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicWebhooksProviderRoute: typeof ApiPublicWebhooksProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calls': {
      id: '/dashboard/calls'
      path: '/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof DashboardCallsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/knowledge': {
      id: '/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/numbers': {
      id: '/dashboard/numbers'
      path: '/numbers'
      fullPath: '/dashboard/numbers'
      preLoaderRoute: typeof DashboardNumbersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/voice': {
      id: '/dashboard/voice'
      path: '/voice'
      fullPath: '/dashboard/voice'
      preLoaderRoute: typeof DashboardVoiceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/companies/$companyId': {
      id: '/admin_/companies/$companyId'
      path: '/admin/companies/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AdminCompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/$job': {
      id: '/api/cron/$job'
      path: '/api/cron/$job'
      fullPath: '/api/cron/$job'
      preLoaderRoute: typeof ApiCronJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/$provider': {
      id: '/api/public/webhooks/$provider'
      path: '/api/public/webhooks/$provider'
      fullPath: '/api/public/webhooks/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCallsRoute: typeof DashboardCallsRoute
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardKnowledgeRoute: typeof DashboardKnowledgeRoute
  DashboardNumbersRoute: typeof DashboardNumbersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardVoiceRoute: typeof DashboardVoiceRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCallsRoute: DashboardCallsRoute,
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardKnowledgeRoute: DashboardKnowledgeRoute,
  DashboardNumbersRoute: DashboardNumbersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardVoiceRoute: DashboardVoiceRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  AdminCompaniesCompanyIdRoute: AdminCompaniesCompanyIdRoute,
  ApiCronJobRoute: ApiCronJobRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicWebhooksProviderRoute: ApiPublicWebhooksProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
